In [1]:
import torch

In [4]:
randint = torch.randint(-100,100,(6,))#Generates a random tensor from -100 to 100
print(randint)

tensor([ 93, -31,  11, -80,  36, -66])


In [7]:
tensor = torch.tensor([[1,2],[3,4],[5,6],[7,8]])
tensor

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [9]:
tensorZero = torch.zeros(5,6)
tensorZero

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [10]:
tensorOne = torch.ones(1,2)
tensorOne

tensor([[1., 1.]])

In [14]:
arange = torch.arange(7)
arange

tensor([0, 1, 2, 3, 4, 5, 6])

In [16]:
linspace = torch.linspace(3, 10, steps = 5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [17]:
logspace = torch.logspace(start=-10, end=10, steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [20]:
eye = torch.eye(3)
eye

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [29]:
a = torch.empty((2,3), dtype=torch.int64)
print(a)
b = torch.tensor([[1,2,3],[4,5,6]])
print(b)
empty_like = torch.empty_like(a)
print(empty_like)
empty_like2 = torch.empty_like(b)
print(empty_like2)

tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([[4176243335152,             0,             0],
        [            0,             0,             0]])
